In [ ]:
!pip install ipython-autotime


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.6 MB/s eta 0:00:00


In [ ]:
%load_ext autotime

time: 2.43 ms (started: 2024-01-18 10:38:57 +00:00)


In [ ]:
# connect colab notebook to drive
from google.colab import drive

# mount google drive
drive.mount('/content/gdrive')

# change directory to project's directory
%cd /content/gdrive/My Drive/predict_credit_card_default

Mounted at /content/gdrive
[Errno 2] No such file or directory: '/content/gdrive/My Drive/predict_credit_card_default'
/content
time: 22.7 s (started: 2024-01-18 10:39:00 +00:00)


In [ ]:
# import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# load the dataset
data = pd.read_excel('data.xlsx', header = 1)

# check
data.tail()


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[5 rows x 25 columns]

time: 6.93 s (started: 2024-01-18 11:26:42 +00:00)


In [ ]:
# rename PAY_0 and default.payment.next.month columns
data.rename(columns={'PAY_0': 'PAY_1',
                     'default payment next month': 'default'},
            inplace = True)

# check
data.head()


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 25 columns]

time: 12.7 ms (started: 2024-01-18 11:26:53 +00:00)


In [ ]:
# Check for missing values in the dataset
data.isnull().sum()


ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
default      0
dtype: int64

time: 8.65 ms (started: 2024-01-18 11:26:56 +00:00)


In [ ]:
!pip install pandas-profiling

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.8/357.8 kB 14.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.9/381.9 kB 32.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 14.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.1/686.1 kB 35.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 31.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 37.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 49.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 87.5 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=f3c251e6e1699b7703831c7fa0f8d595647d2966b424a24f9a3965bbae0c8065
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d0

In [ ]:
# get the dependent and independent variables
X = data.drop(['default', 'ID'], 1)
y = data['default']

time: 6.4 ms (started: 2024-01-18 11:27:46 +00:00)


<ipython-input-11-1225fccae281>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = data.drop(['default', 'ID'], 1)


In [ ]:
!pip install pandas-profiling==3.0.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.5/248.5 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.0/103.0 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 23.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.0/354.0 kB 39.8 MB/s eta 0:00:00
  Attempting uninstall: tangled-up-in-unicode
    Found existing installation: tangled-up-in-unicode 0.2.0
    Uninstalling tangled-up-in-unicode-0.2.0:
      Successfully uninstalled tangled-up-in-unicode-0.2.0
  Attempting uninstall: multimethod
    Found existing installation: multimethod 1.10
    Uninstalling multimethod-1.10:
      Successfully uninstalled multimethod-1.10
  Attempting uninstall: visions
    Found existing installation: visions 0.7.5
    Uninstalling visions-0.7.5:
      Successfully uninstalled visions-0.7.5
  Attempting uninstall: pandas-profiling
    Found existing installation: pandas-profiling 3.6.6
    Uninstalling pandas-profiling-3.6.6

In [ ]:
# import pandas_profiling
# # #create a pandas profile report for the dataset
# profile = pandas_profiling.ProfileReport(data, minimal=True)

# # #save the report in a html document
# profile.to_file('credi_card_default_EDA.html')

time: 317 µs (started: 2024-01-18 11:28:43 +00:00)


In [ ]:

# bin some values in the education column
X[(X['EDUCATION'] == 0) | (X['EDUCATION'] == 5) | (X['EDUCATION'] == 6)] = 4

X['EDUCATION'].value_counts()


2    14030
1    10585
3     4917
4      468
Name: EDUCATION, dtype: int64

time: 12.2 ms (started: 2024-01-18 11:28:47 +00:00)


In [ ]:
# import package for splitting data
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.model_selection import GridSearchCV

#split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=33)

# import standard scalar
from sklearn.preprocessing import StandardScaler

# instantiate the standard scalar
ss = StandardScaler()
X_train_ss = ss.fit_transform(X_train)
X_test_ss = ss.transform(X_test)

# check
X_train_ss

array([[-1.19482966,  0.67320416,  0.21251328, ..., -0.26855851,
        -0.28198535, -0.25332386],
       [-0.73314976, -1.14735997, -1.13124751, ..., -0.14411153,
        -0.31741068, -0.28694982],
       [-1.04093636, -1.14735997,  1.55627407, ..., -0.30100384,
        -0.31741068, -0.28694982],
       ...,
       [-0.42536315, -1.14735997, -1.13124751, ..., -0.18772759,
        -0.17101282, -0.17486329],
       [-0.3484165 ,  0.67320416,  1.55627407, ..., -0.25343409,
        -0.18288835, -0.26677424],
       [ 1.49830313,  0.67320416,  0.21251328, ...,  1.41552363,
        -0.1987895 , -0.16864249]])

time: 29 ms (started: 2024-01-18 11:28:50 +00:00)


In [ ]:
#NEURAL NETWORKS:

# import the keras module
import keras

# import the sequential model
from keras.models import Sequential

# import dense layer that connects all nodes in the previous layer to nodes in current layer
from keras.layers import Dense

# import optimizers
from keras.optimizers import SGD

# import dropout
from keras.layers import Dropout

# as recommended in the original paper on Dropout, a constraint is imposed on the weights for each hidden layer,
# ensuring that the maximum norm of the weights does not exceed a value of 3.
# This is done by setting the kernel_constraint argument on the Dense class when constructing the layers.
from keras.constraints import MaxNorm

# instantiate the model
model = Sequential()

# Add the input layer  which transforms each input to a 1-dimensional array
model.add(keras.layers.Flatten(input_shape = (23, )))

# Add the first hidden layer with 2000 nodes, specify activation='relu'
model.add(Dense(2000, activation='relu', kernel_constraint=MaxNorm(3)))

# Add the first dropout layer
model.add(Dropout(0.2))

# Add a second hidden Dense layer. This should have 1000 nodes and a 'relu' activation.
model.add(Dense(1000, activation='relu', kernel_constraint=MaxNorm(3)))

# Add a second dropout layer
model.add(Dropout(0.2))

# Add a third hidden Dense layer. This should have 1000 nodes and a 'relu' activation.
model.add(Dense(500, activation='relu', kernel_constraint=MaxNorm(3)))

# Add the third dropout layer
model.add(Dropout(0.2))

# Finally, add an output layer, which is a Dense layer with 2 classes. Use sigmoid activation function for binary classification.
model.add(Dense(1, activation='sigmoid'))

# see the summary of the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 23)                0         
                                                                 
 dense (Dense)               (None, 2000)              48000     
                                                                 
 dropout (Dropout)           (None, 2000)              0         
                                                                 
 dense_1 (Dense)             (None, 1000)              2001000   
                                                                 
 dropout_1 (Dropout)         (None, 1000)              0         
                                                                 
 dense_2 (Dense)             (None, 500)               500500    
                                                                 
 dropout_2 (Dropout)         (None, 500)               0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Assume X_train and y_train are your features and labels
# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train_ss = scaler.fit_transform(X_train)
X_val_ss = scaler.transform(X_val)

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Defines model callbacks
model_path = './model_dir/model.h5'
my_callbacks = [keras.callbacks.ModelCheckpoint(model_path, monitor='loss'),
                keras.callbacks.EarlyStopping(patience=3, monitor='loss')
                ]

# Fit the model on the train dataset
history = model.fit(X_train_ss, y_train, validation_data=(X_val_ss, y_val), epochs=100, callbacks=my_callbacks)


Epoch 1/100
540/540 [==============================] - 16s 29ms/step - loss: 0.3483 - accuracy: 0.8548 - val_loss: 0.3388 - val_accuracy: 0.8637
Epoch 2/100
  5/540 [..............................] - ETA: 14s - loss: 0.3475 - accuracy: 0.8500

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


540/540 [==============================] - 14s 27ms/step - loss: 0.3360 - accuracy: 0.8602 - val_loss: 0.3432 - val_accuracy: 0.8569
Epoch 3/100
540/540 [==============================] - 15s 29ms/step - loss: 0.3352 - accuracy: 0.8594 - val_loss: 0.3658 - val_accuracy: 0.8509
Epoch 4/100
540/540 [==============================] - 15s 27ms/step - loss: 0.3333 - accuracy: 0.8597 - val_loss: 0.3582 - val_accuracy: 0.8512
Epoch 5/100
540/540 [==============================] - 14s 25ms/step - loss: 0.3255 - accuracy: 0.8620 - val_loss: 0.3741 - val_accuracy: 0.8454
Epoch 6/100
540/540 [==============================] - 13s 25ms/step - loss: 0.3195 - accuracy: 0.8667 - val_loss: 0.3882 - val_accuracy: 0.8403
Epoch 7/100
540/540 [==============================] - 15s 27ms/step - loss: 0.3204 - accuracy: 0.8655 - val_loss: 0.3922 - val_accuracy: 0.8368
Epoch 8/100
540/540 [==============================] - 14s 26ms/step - loss: 0.3182 - accuracy: 0.8650 - val_loss: 0.3991 - val_accuracy: 0.84

In [ ]:
loaded_model_1 = keras.models.load_model('./model_dir/model.h5')

# Assuming you have X_test_ss and y_test defined
pred_prob = loaded_model_1.predict(X_test_ss)
nn_pred = (pred_prob > 0.5).astype(int).ravel()  # Apply threshold (0.5 in this case)
nn_acc = accuracy_score(y_test, nn_pred)
nn_f1 = f1_score(y_test, nn_pred)
nn_roc_auc = roc_auc_score(y_test, pred_prob)

print(f'Accuracy score of ANN without class imbalance consideration is {nn_acc}', '\n')
print(f'ROC_AUC score of ANN without class imbalance consideration is {nn_roc_auc}', '\n')
print(f'The f1 score of ANN without class imbalance consideration is {nn_f1}', '\n')
print('The confusion matrix of ANN without class imbalance consideration is:', '\n', f'{confusion_matrix(y_test, nn_pred)}')


94/94 [==============================] - 1s 9ms/step
Accuracy score of ANN without class imbalance consideration is 0.7896666666666666 

ROC_AUC score of ANN without class imbalance consideration is 0.7120662359278986 

The f1 score of ANN without class imbalance consideration is 0.44109831709477415 

The confusion matrix of ANN without class imbalance consideration is: 
 [[2120  217]
 [ 414  249]]
time: 2.01 s (started: 2024-01-18 12:25:56 +00:00)


In [ ]:
#Create a network that takes class imbalance into consideration

# instantiate the model
model_2 = Sequential()

# Add the input layer  which transforms each input to a 1-dimensional array
model_2.add(keras.layers.Flatten(input_shape = (23, )))

# Add the first hidden layer with 4000 nodes, specify activation='relu'
model_2.add(Dense(4000, activation='relu', kernel_constraint=MaxNorm(4)))

# Add the first dropout layer to reduce overfitting and ensure randomization of layers
model_2.add(Dropout(0.2))

# Add a second hidden Dense layer. This should have 3000 nodes and a 'relu' activation.
model_2.add(Dense(2000, activation='relu', kernel_constraint=MaxNorm(4)))

# Add a second dropout layer
model_2.add(Dropout(0.2))

# Add a third hidden Dense layer. This should have 1000 nodes and a 'relu' activation.
model_2.add(Dense(1000, activation='relu', kernel_constraint=MaxNorm(4)))

# Add the third dropout layer
model_2.add(Dropout(0.2))

# Finally, add an output layer, which is a Dense layer with 2 classes. Use sigmoid activation function for binary classification.
model_2.add(Dense(1, activation='sigmoid'))

# see the summary of the model
model_2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 23)                0         
                                                                 
 dense_4 (Dense)             (None, 4000)              96000     
                                                                 
 dropout_3 (Dropout)         (None, 4000)              0         
                                                                 
 dense_5 (Dense)             (None, 2000)              8002000   
                                                                 
 dropout_4 (Dropout)         (None, 2000)              0         
                                                                 
 dense_6 (Dense)             (None, 1000)              2001000   
                                                                 
 dropout_5 (Dropout)         (None, 1000)             

In [ ]:
model_2.compile(loss='binary_crossentropy', optimizer=SGD(learning_rate=0.00001, momentum=0.99), metrics=['accuracy'])


time: 17 ms (started: 2024-01-18 12:30:46 +00:00)


In [ ]:
# Defines model callbacks
model_path_2 = './model_dir/model_2.h5'
my_callbacks_2 = [keras.callbacks.ModelCheckpoint(model_path_2, save_best_only=True, monitor='loss'),
                keras.callbacks.EarlyStopping(patience=3, monitor='loss')
                ]


time: 526 µs (started: 2024-01-18 12:31:00 +00:00)


In [ ]:

# define the weights using the inverse of the ratio ~ 4:1
weights = {0:1, 1:4}

# fit the model
history_2 = model_2.fit(X_train_ss, y_train, epochs=100, callbacks=[my_callbacks_2], class_weight=weights)

Epoch 1/100
540/540 [==============================] - 55s 100ms/step - loss: 1.1226 - accuracy: 0.3785
Epoch 2/100
  1/540 [..............................] - ETA: 43s - loss: 1.1368 - accuracy: 0.3438

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


540/540 [==============================] - 47s 87ms/step - loss: 1.0837 - accuracy: 0.4525
Epoch 3/100
540/540 [==============================] - 45s 83ms/step - loss: 1.0593 - accuracy: 0.5505
Epoch 4/100
540/540 [==============================] - 44s 82ms/step - loss: 1.0430 - accuracy: 0.5900
Epoch 5/100
540/540 [==============================] - 46s 85ms/step - loss: 1.0306 - accuracy: 0.6300
Epoch 6/100
540/540 [==============================] - 44s 81ms/step - loss: 1.0197 - accuracy: 0.6488
Epoch 7/100
540/540 [==============================] - 45s 83ms/step - loss: 1.0098 - accuracy: 0.6466
Epoch 8/100
540/540 [==============================] - 44s 81ms/step - loss: 1.0029 - accuracy: 0.6692
Epoch 9/100
540/540 [==============================] - 44s 82ms/step - loss: 0.9981 - accuracy: 0.6714
Epoch 10/100
540/540 [==============================] - 44s 82ms/step - loss: 0.9916 - accuracy: 0.6845
Epoch 11/100
540/540 [==============================] - 44s 81ms/step - loss: 0.9886

In [ ]:
loaded_model_2 = keras.models.load_model('./model_dir/model_2.h5')

pred_prob_2 = loaded_model_2.predict(X_test_ss)
nn_pred_2 = (pred_prob_2 > 0.5).astype(int)  # Apply threshold (e.g., 0.5 for binary classification)
nn_acc_2 = accuracy_score(y_test, nn_pred_2)
nn_f1_2 = f1_score(y_test, nn_pred_2)
nn_roc_auc_2 = roc_auc_score(y_test, pred_prob_2)

print(f'Accuracy score of ANN with class imbalance consideration is {nn_acc_2}', '\n')
print(f'ROC_AUC score of ANN with class imbalance consideration is {nn_roc_auc_2}', '\n')
print(f'The f1 score of ANN with class imbalance consideration is {nn_f1_2}', '\n')
print('The confusion matrix of ANN with class imbalance consideration is:', '\n', f'{confusion_matrix(y_test, nn_pred_2)}')


94/94 [==============================] - 1s 14ms/step
Accuracy score of ANN with class imbalance consideration is 0.7383333333333333 

ROC_AUC score of ANN with class imbalance consideration is 0.7791098796913188 

The f1 score of ANN with class imbalance consideration is 0.5268233875828813 

The confusion matrix of ANN with class imbalance consideration is: 
 [[1778  559]
 [ 226  437]]
time: 3.28 s (started: 2024-01-18 13:41:26 +00:00)


In [ ]:
#MultiNomial Naive Bayes

# import minmaxscalar
from sklearn.preprocessing import MinMaxScaler

# import the naive bayes classifier
from sklearn.naive_bayes import MultinomialNB

# import gridsearch cv
from sklearn.model_selection import GridSearchCV

# instantiate minmax scalar
mms = MinMaxScaler()

X_train_mm = mms.fit_transform(X_train)
X_test_mm = mms.transform(X_test)

# instantiate the classifier with default parameters
mnb_model = MultinomialNB()

# define search space
space_mnb = dict()
space_mnb['alpha'] = [0.1, 0.01, 0.001, 0.0001, 0.00001, 1.0, 2.0]

# grid search the hyper parameter
mnb_search = GridSearchCV(estimator=mnb_model, param_grid=space_mnb, cv=10, n_jobs=-1)


# fit the mnb classifier on the train set
mnb_result = mnb_search.fit(X_train_mm, y_train)

# print the best score from the search
print(f'The best score from the search is {mnb_result.best_score_}', '\n')

# print the best parameter
print(f'The best parameter from the search is {mnb_result.best_params_}')

The best score from the search is 0.7762152777777777 

The best parameter from the search is {'alpha': 0.1}
time: 2.97 s (started: 2024-01-18 13:42:24 +00:00)


In [ ]:
#XGB
# get the ratio of class values in the default column
from collections import Counter

counter = Counter(y)

estimate = counter[0] / counter[1]
estimate

3.5207956600361663

time: 13.6 ms (started: 2024-01-18 13:43:53 +00:00)


In [ ]:
import xgboost as xgb

# instantiate an XGB classifier that accounts for class imbalance
xgb_model= xgb.XGBClassifier(scale_pos_weight=round(estimate, 1))

xgb_model.fit(X_train_ss, y_train)

xgb_pred = xgb_model.predict(X_test_ss)

xgb_acc = accuracy_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)
xgb_roc_auc = roc_auc_score(y_test, xgb_pred)


print(f'Accuracy score of XGB is {xgb_acc}', '\n')
print(f'ROC_AUC score of XGB is {xgb_roc_auc}', '\n')
print(f'The f1 score of XGB is {xgb_f1}', '\n')
print('The confusion matrix of XGB is:', '\n', f'{confusion_matrix(y_test, xgb_pred)}',)

Accuracy score of XGB is 0.7876666666666666 

ROC_AUC score of XGB is 0.6244063143179658 

The f1 score of XGB is 0.4085422469823584 

The confusion matrix of XGB is: 
 [[2143  194]
 [ 443  220]]
time: 683 ms (started: 2024-01-18 13:44:06 +00:00)


In [ ]:
# check the shape of the data
data.shape

(30000, 25)

time: 3.16 ms (started: 2024-01-18 13:44:34 +00:00)


In [ ]:
# Isolate the predicted feature
target = data['default']

# check
print(target.shape)

# drop ID and default columns
data.drop(['ID', 'default'], axis=1, inplace=True)

# check
data.head()

(30000,)


LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -2  ...        689          0          0          0         0       689   
1      0  ...       2682       3272       3455       3261         0      1000   
2      0  ...      13559      14331      14948      15549      1518      1500   
3      0  ...      49291      28314      28959      29547      2000      2019   
4      0  ...      35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         0         0         0         0  
1      1000      1000         0      2000  
2      1000      1000      1000      5000  
3      1200      1100      1069      1000  
4     10000      9000       689       679  

[5 rows x 23 columns]

time: 39 ms (started: 2024-01-18 13:44:46 +00:00)


In [ ]:
# check the values of the education column
data['EDUCATION'].value_counts()

2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: EDUCATION, dtype: int64

time: 8.98 ms (started: 2024-01-18 13:45:02 +00:00)


In [ ]:
# bin values of the education column
data[(data['EDUCATION'] == 0) | (data['EDUCATION'] == 5) | (data['EDUCATION'] == 6)] = 4

# check
data['EDUCATION'].value_counts()

2    14030
1    10585
3     4917
4      468
Name: EDUCATION, dtype: int64

time: 11.4 ms (started: 2024-01-18 13:45:15 +00:00)


In [ ]:
#Preprocess the data
# import the scaler
from sklearn.preprocessing import StandardScaler

# import joblib for saving and loading binary files
from  joblib import dump
from joblib import load

# instantiate the scaler
scaler = StandardScaler()

# scale the features data using standard scaler
scaler.fit(data)

# save the scaler
dump(scaler, 'scaler.joblib')

['scaler.joblib']

time: 17 ms (started: 2024-01-18 13:45:41 +00:00)


In [ ]:
# check the scaler mean and standard deviations
print(scaler.mean_, '\n'); scaler.scale_


[ 1.65561502e+05  1.63100000e+00  1.84226667e+00  1.58076667e+00
  3.51064667e+01  3.09666667e-02 -8.39333333e-02 -1.15633333e-01
 -1.70066667e-01 -2.15200000e-01 -2.38500000e-01  5.03164653e+04
  4.83344410e+04  4.62154227e+04  4.25832832e+04  3.97323530e+04
  3.83719462e+04  5.58849837e+03  5.82144120e+03  5.13657327e+03
  4.76963970e+03  4.73512893e+03  5.11648983e+03] 



array([1.30360641e+05, 5.49398762e-01, 7.44482054e-01, 5.80755323e-01,
       9.75462958e+00, 1.19747278e+00, 1.27164796e+00, 1.27318325e+00,
       1.24945748e+00, 1.21784877e+00, 1.23359275e+00, 7.31004605e+04,
       7.06607261e+04, 6.88607994e+04, 6.39480431e+04, 6.04612734e+04,
       5.92820578e+04, 1.64941099e+04, 2.29447389e+04, 1.74765097e+04,
       1.56169251e+04, 1.51522715e+04, 1.75499039e+04])

time: 9.2 ms (started: 2024-01-18 13:45:51 +00:00)


In [ ]:

# load the saved scaler
load_scaler = load('scaler.joblib')

# check
load_scaler


StandardScaler()

time: 10.3 ms (started: 2024-01-18 13:46:02 +00:00)


In [ ]:
# transform the entire data
scaled_data = load_scaler.transform(data)

# check
scaled_data

array([[-1.11660622,  0.6716433 ,  0.21186989, ..., -0.30541478,
        -0.31250291, -0.29153948],
       [-0.34950351,  0.6716433 ,  0.21186989, ..., -0.24138169,
        -0.31250291, -0.17757874],
       [-0.57963432,  0.6716433 ,  0.21186989, ..., -0.24138169,
        -0.2465062 , -0.00663763],
       ...,
       [-1.03989595, -1.14852825,  0.21186989, ..., -0.03647579,
        -0.1805095 , -0.11490033],
       [-0.65634459, -1.14852825,  1.55508562, ..., -0.18208704,
         3.1829466 , -0.18874689],
       [-0.8864754 , -1.14852825,  0.21186989, ..., -0.24138169,
        -0.2465062 , -0.23455911]])

time: 9.17 ms (started: 2024-01-18 13:46:19 +00:00)


In [ ]:
import xgboost as xgb

# instantiate an XGB classifier that accounts for class imbalance
xgb_model_all= xgb.XGBClassifier(scale_pos_weight=round(estimate, 1))

xgb_model_all.fit(scaled_data, y)

xgb_all_pred = xgb_model_all.predict(X_test_ss)

xgb_all_acc = accuracy_score(y_test, xgb_all_pred)
xgb_all_f1 = f1_score(y_test, xgb_all_pred)
xgb_all_roc_auc = roc_auc_score(y_test, xgb_all_pred)


print(f'Accuracy score of XGB Trained on entire data is {xgb_all_acc}', '\n')
print(f'ROC_AUC score of XGB Trained on entire data is {xgb_all_roc_auc}', '\n')
print(f'The f1 score of XGB Trained on entire data is {xgb_all_f1}', '\n')
print('The confusion matrix of XGB Trained on entire data is:', '\n', f'{confusion_matrix(y_test, xgb_all_pred)}')

Accuracy score of XGB Trained on entire data is 0.818 

ROC_AUC score of XGB Trained on entire data is 0.6644032551304317 

The f1 score of XGB Trained on entire data is 0.48587570621468923 

The confusion matrix of XGB Trained on entire data is: 
 [[2196  141]
 [ 405  258]]
time: 1.58 s (started: 2024-01-18 13:46:32 +00:00)


In [ ]:
#Save XGBoost MODEL
dump(xgb_model_all, 'xgb_model.joblib')

['xgb_model.joblib']

time: 7.74 ms (started: 2024-01-18 13:47:34 +00:00)


In [ ]:
#Testing with new real time data

# load model
loaded_model = load('xgb_model.joblib')

# scale the input
Raw_Data =  np.array([20000, 1, 5, 2, 22, 2, 0, 0, 0, 0, 0, 18565, 17204, 17285, 18085, 11205, 5982, 0, 1200, 1000, 500, 1000, 0]).reshape(1, -1)
scaled_input = load_scaler.transform(Raw_Data)

# check
scaled_input


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.11660622, -1.14852825,  4.24151706,  0.72187601, -1.343615  ,
         1.64432408,  0.06600359,  0.09082222,  0.13611241,  0.17670503,
         0.19333771, -0.43435383, -0.44056214, -0.42012906, -0.38309668,
        -0.47182852, -0.54637014, -0.33881782, -0.20141616, -0.23669333,
        -0.27339823, -0.2465062 , -0.29153948]])

time: 11.1 ms (started: 2024-01-18 14:06:42 +00:00)


In [ ]:

from joblib import load
import numpy as np

# Load the model
loaded_model = load('xgb_model.joblib')

# Scale the input (assuming you have a scaler saved as load_scaler)
# Make sure load_scaler is defined before this point
Raw_Data = np.array([20000, 1, 5, 2, 22, 2, 0, 0, 0, 0, 0, 18565, 17204, 17285, 18085, 11205, 5982, 0, 1200, 1000, 500, 1000, 0]).reshape(1, -1)
scaled_input = load_scaler.transform(Raw_Data)

# Check the scaled input
print(scaled_input)

# Get prediction result
result = loaded_model.predict(scaled_input)

print(result)

# Assuming result is a 1D array (class labels), select the first element
prediction = result[0]

if prediction == 0:  # adjust based on your class labels
    print('Defaulter')
else:
    print('Non-Defaulter')


[[-1.11660622 -1.14852825  4.24151706  0.72187601 -1.343615    1.64432408
   0.06600359  0.09082222  0.13611241  0.17670503  0.19333771 -0.43435383
  -0.44056214 -0.42012906 -0.38309668 -0.47182852 -0.54637014 -0.33881782
  -0.20141616 -0.23669333 -0.27339823 -0.2465062  -0.29153948]]
[1]
Non-Defaulter
time: 18.5 ms (started: 2024-01-18 14:10:11 +00:00)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
